Repository readmeio/oas-normalize, pull requests merged in 2023-09, with the labels that each got.

#290 feat: support for esm builds
  .npmrc
  __tests__/index.test.ts
  package-lock.json
  package.json
  tsconfig.json
  tsup.config.ts
Labels: enhancement

#292 feat: dropping support for node 14 and 16
  .eslintrc
  .github/dependabot.yml
  .github/workflows/ci.yml
  __tests__/index.test.ts
  package-lock.json
  package.json
  src/index.ts
Labels: enhancement

#294 fix: get exports working in TS `nodeNext`
  package.json
Labels: bug

#295 fix: reorganize exports to get default export working
  __tests__/index.test.ts
  package.json
  src/index.ts
  src/lib/types.ts
  tsup.config.ts
Labels: bug

#296 chore(deps): bump
  package-lock.json
  package.json
Labels: dependencies
